# Generated by Django 5.1.1 on 2024-09-15 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customuser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table=None,
        ),
    ]
