# Generated by Django 5.1.1 on 2024-09-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sended_message',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время отправки'),
        ),
    ]
