# Generated by Django 5.1.1 on 2024-09-15 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_customuser_sended_message'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='custom_user',
        ),
    ]
