# Generated by Django 5.1.1 on 2024-09-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='avatar.png', upload_to='avatars', verbose_name='Аватар'),
        ),
    ]
