# Generated by Django 5.1.1 on 2024-09-24 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
                'db_table': 'collection',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Премиум'),
        ),
        migrations.AddField(
            model_name='item',
            name='only_for_premium',
            field=models.BooleanField(default=False, verbose_name='Только для премиум'),
        ),
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_see_other', models.BooleanField(default=False, verbose_name='Могут видеть другие пользователи')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.collection', verbose_name='Коллекция')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользовательская коллекция',
                'verbose_name_plural': 'Пользовательские коллекции',
                'db_table': 'user_collection',
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('good', 'Хорошее'), ('bad', 'Плохое')], max_length=100, verbose_name='Качество')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item', verbose_name='Предмет')),
                ('user_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usercollection', verbose_name='Пользовательская коллекция')),
            ],
            options={
                'verbose_name': 'Предмет в коллекции',
                'verbose_name_plural': 'Предметы в коллекции',
                'db_table': 'collection_item',
            },
        ),
        migrations.DeleteModel(
            name='UserItem',
        ),
    ]
