# Generated by Django 5.1.1 on 2024-09-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_collection_customuser_is_premium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user_counter',
        ),
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
